### ISSUE TITLE
Comments on SRS

### ISSUE THREAD

**Issue by smiths** [slimpotatoes/STEM_Moire_GPA#10]
Please look at the comments on your SRS in commit a9c09592ff19266082529b1f4bb3774a051fd268

**Comment by slimpotatoes** [comment]
Thank you very much for the comments. I revised the SRS document accordingly and took the opportunity to modify slightly other sections. I let some of your comments in the document (like the one about the software/user responsibilities) since we might come back on those aspects later on and I don't want to forget those points.
