### ISSUE TITLE
Test Plan (Scope): Reasonable Error

### ISSUE THREAD

**Issue by GenevaS** [slimpotatoes/STEM_Moire_GPA#11]
"Reasonable error" is mentioned in the test plan scope, but it is not quantified. Can you specify what the tolerance for error is (perhaps in relative terms)? It is difficult to maintain a consistent judgement of the software's error tolerance between reviewers if the threshold value is not set.

**Comment by slimpotatoes** [comment]
Hi @GenevaS,

It's an excellent question perfectly targeting my lack of precise knowledge on the error provided by STEM Moire GPA software :). For the moment, I honestly don't know what to expect. After thinking about the processing errors, I manage to identify the GPA algorithm as one of the greatest source of errors. Then I get stuck when I tried to estimate the errors analytically with some easy functions because the algorithm (or the model) is already based on approximations. Moreover the effect of one input (the mask) leads to a complex analytical description relatively difficult to test (it could be a research project on its own). From that point, I realised that I won't be able to test the GPA calculations easily (I actually wonder if this has been properly realised once). 

My choice to use GPA algorithm is not based on a clear technical argument except that the algorithm is very commonly used in our research community. The course (so as your comment) is actually questioning my choice because I never really thought about quantitatively estimating the error of the processing method. I still have a vague idea on how the processing is bringing errors but I'm stuck to repeat what I have read or have been told. To answer your comment, I put an absurd high tolerance for the error (50% of relative error) in the test plan document. I think you're right I should at least put some limit even if physically I expect a better performance regarding the error. I will adjust the tolerance limit once I have studied what error to expect from the GPA algorithm.
