### ISSUE TITLE
Test Plan (Test Cases): Representative Examples

### ISSUE THREAD

**Issue by GenevaS** [slimpotatoes/STEM_Moire_GPA#13]
Many of your test cases have equations rather than concrete values. Are you testing them symbolically? If not, you should pick a set of concrete input and output values to represent each test case. This will also make it easier to specify the cases in your unit testing framework and perhaps identify edge cases that need to be handled differently.

**Comment by slimpotatoes** [comment]
Very good comment (joining the comments from @smiths ) :). The test cases you are referring to are not planned to be tested symbolically so specific dataset (inputs and expected outputs) need to be generated in the appropriate format (2d arrays). Technically, I would have to also test the test functions ... and I realise now how testing software can be a full time job. 

I decided to not specify the values for the parameters because it helped me in visualising physically (or mathematically) what I wanted to test. At that time, I didn't feel confident in taking decision by jumping right away into designing specific tests dataset. As a consequence, the document is indeed vague in the implementation of those test cases. Keeping the description symbolic, helps me in carrying the physical meaning of the data. One of my goals is for example to express the evolution of the error as function of the input parameters (one of my biggest motivation driver of the course project). With a clearer understanding, I could now make the decisions and modify the document but I'm running out of time at the moment.

So, to address your comment, I added a clarification in the document saying that the test cases are still described at the physical/mathematical level and some decisions are going to be performed and will be documented later. Once I generated the test dataset (inputs and expected outputs), I will describe them and refer to them when needed in the tests cases.
