### ISSUE TITLE
Test Plan (Non-Functional Test 8): Separating Accuracy and Precision

### ISSUE THREAD

**Issue by GenevaS** [slimpotatoes/STEM_Moire_GPA#14]
I might be misunderstanding this test, but it seems like you are doing two separate tests - one with and one without noise. These seem like two separate cases to me. Perhaps split them into two tests where the test without noise is a prerequisite to the test with noise?

**Comment by slimpotatoes** [comment]
It is true that I can separate them, it is just I found it convenient to write them both at once considering the noise as a parameter of the test. 

Noise = 0, is one possible test example and represent the ideal case with a pure data not affected with random noise. I expect this test to not be equal to the expected results because of the GPA algorithm (even with the most appropriate inputs). The error results from the black box test might be physically interpreted as an "inaccuracy" including all possible errors. 

Noise = Gaussian Noise (at a certain strength) represent the "real" case of a pure data affected by the environment. The error from this test is expected to include the inaccuracy from N=0 and the error from randomness. Depending on how precision is defined, either only the error from randomness is extracted or the global error is considered. 

Technically, the inaccuracy definition is not correct. I expect the inaccuracy to also vary as a function of the strain (not planned to be tested) even in the pure data without noise. So I should not call it "inaccuracy" but I wanted to try to differentiate the effect from a random noise and from a different input.  At the end, I am only testing precision of the method with different level of noise. The difference is just purely based on terminology.
