### ISSUE TITLE
Test Plan (Non-Functional Test 15): Testing Tags

### ISSUE THREAD

**Issue by GenevaS** [slimpotatoes/STEM_Moire_GPA#16]
I don't understand what this is testing for exactly. What are you testing here? Are you testing to see if all the tags exist in the software? Are you testing to see if switches are set properly based on the read tags? Please clarify.

**Comment by slimpotatoes** [comment]
Ohhh I forgot to even test if the tags exist ... Test 15 was designed to check if the correct tags were loaded when importing the data because some tags can have the same format and correspond to completely different physical aspect. For example, the calibration and the high tension tag are both real numbers and it's possible to confuse them when importing the data. So I clarified that point but I will need to add more tests on the "dm3" format.
