### ISSUE TITLE
Test Plan (Non-Functional Test 22): Automated comparison of images?

### ISSUE THREAD

**Issue by GenevaS** [slimpotatoes/STEM_Moire_GPA#18]
Will you be automating the comparison between the output image and a manually generated image? How will you ensure that the "correct" image is correct?

**Comment by slimpotatoes** [comment]
I assume you relate the "correct" image as the manually generated image. I will join your comment to another one since the manually generated image is part of the test dataset I have to make. You're right I  have to test that the generate image is the proper one. I'm optimistic in this task to not be too difficult if I choose easy proper test cases. I will document it later.

Thanks for your great comments @GenevaS . There are very helpful, I really appreciate them :).
