### ISSUE TITLE
Generic GUI and Stem Moire GPA GUI should be in the same module

### ISSUE THREAD

**Issue by renjiezhang** [slimpotatoes/STEM_Moire_GPA#22]
Generic GUI is in software decision and Stem Moire GUI is in behaviour-hiding. I think they should be in the same module or at least be in the same category.

**Comment by renjiezhang** [comment]
@smiths

**Comment by slimpotatoes** [comment]
I understand your comment, my MG is not clear on that point and actually I don't know how to be clear with mu GUI modules with a few sentences describing the services. 

In the SRS, some requirements expect a environment for the user to input some parameters, display some intermediate data on which an interaction with the user is required, and display the strain maps. So I need to have a decision hiding behaviour module meeting these requirements. I decided to interface with the user by designing a STEM Moire GPA GUI specific to STEM Moire GPA needs. This GUI will be composed of windows, buttons, basic drawing elements to meet the requirements. In the same time, it is possible to display other type of data that are not mentioned in the functional requirement. For that matter, I imagined a more generic GUI/plot module that will be a software decision module. I then can agree that the module connections are questionable. I can't describe it in my mind properly at the moment. 

To be complete, the description above is not enough detailed since I anticipated some other issues in the execution flow of STEM Moire GPA. Multiple inputs have to be provided by the user at different stage of the execution and on different type of data. So the control module could organise the flow and wait for the user input to happen. I decided to go with another design and let the flow to be organised by the user directly by triggering events in STEM Moire GPA GUI. The control module is uses those events in STEM Moire GPA to use the module called by the user. This aspect is not document yet in the MG document since my ideas are still not fully fixed.

My hope is to see how things connect in the MIS document and probabyl see some issues that will force me to readjust the MG. I will keep your comment in mind and will make a decision once the MIS done.
