### ISSUE TITLE
Phase Module M14 should be in behaviour-hiding section

### ISSUE THREAD

**Issue by renjiezhang** [slimpotatoes/STEM_Moire_GPA#26]
In the SRS, you have the modules Geometrical Phase Analysis for phase. I think it should be in behaviour-hiding think you need to implement it.

**Comment by renjiezhang** [comment]
@smiths

**Comment by slimpotatoes** [comment]
Hi Renie,

Thanks for your comments ;). 

GPA stands for Geometrical Phase Analysis and corresponds to module M6 and is indeed a behaviour hiding module since the ouput from GPA is a functional requirement. I am sorry for the confusion, I didn't mention what the acronym GPA means. So to address your comment, I added the GPA acronym description in the MG document. M14 is a Phase calculation module that is used when doing some basic operation on a phase type of data. The module doesn't correspond to the GPA algorithm but will be used by GPA to perform operations on the Phase. The phase in any cosine or sine function is defined between [-π,π[ (or [0,2π]) so to add/substract "phase type of data" (or any type of operation) specific transformations are performed to keep the phase in the interval [-π,π[. Other more complex operation need the phase to be expressed it in real space so the phase is "unwrapped" . After those operations performed, the phase can to be "wrapped" again to express it in the interval [-π,π[. 

The following wikipedia link is a quick description of the phase wrapping and unwrapping idea https://en.wikipedia.org/wiki/Instantaneous_phase. It's not a very good reference but I will add more details in the MIS document for the Phase calculation module.  It should be clearer in a near future :).
