### ISSUE TITLE
Why is Comments.tex in the .gitignore file?

### ISSUE THREAD

**Issue by smiths** [slimpotatoes/STEM_Moire_GPA#29]
Why isn't Comments.tex under version control and why is it listed in the .gitignore file?  I couldn't compile your Module Guide because I checked out a fresh version of your repo and didn't have a Comments.tex file.  My first thought was that you forgot to put Comments.tex under version control, but the fact that it is in the .gitignore file suggests that this was done on purpose?

**Comment by slimpotatoes** [comment]
Hi @smiths,

It's a mistake from my side. My goal was to make the comment not visible in the .pdf file and just be present the tex file. So I modified the comment.tex file and realised that file is not the same version as in the repo anymore. To not modify it when pushing in the repo, I added it in the .gitignore file thinking that by not tracking the file with git, the file will be untouched in repo... I hoped the file will stay in the repo allowing your comments to be still visible in the .pdf file when you compile it. Reading myself, I realise that it makes no sense I don't know why it comes that way in my mind ... probably because I didn't read the documentation properly (shame on me :( ). 

So I pushed the original comment.tex (with comment visible in the pdf). I will edit the file once the course finished to remove them from the .pdf (by modifying \newif\ifcomments\commentstrue to \newif\ifcomments\commentsfalse) and pushed it in the repo. This way the text file is still compilable and the comments are only present in the tex.file. I like the fact that I can look for comment by searching the keywords "/an" or /wss".

**Comment by smiths** [comment]
Sounds good.  I'm fine if you want to set comments to false.  I can always turn them on myself and compile.  Another version of comment.tex could prompt the user before compiling to see whether they would like comments on or not.  I don't think this is worth the complexity, but it would let you leave the Comments.tex file alone and bind the value at run-time.
