### ISSUE TITLE
Comments in MG

### ISSUE THREAD

**Issue by smiths** [slimpotatoes/STEM_Moire_GPA#30]
For your review, minor comments have been added to your MG in commit cd93b64.

**Comment by slimpotatoes** [comment]
Hi @smiths,

I am letting the comment open since I am modifying the file to be in accordance with the MIS. 

For the small strain assumption, I was targeting an anticipated change in the decomposition of the gradient of the displacement field tensor into the sum of one symmetric tensor (strain) and one anti-symmetric tensor (rotation). Other model with "larger deformation" but still "not too large" exists by adding some extra tensors in the decomposition. The link between the GPA results and what is needed for the for the strain calculation might be more complicated in those cases but potentially doable.

However, i agree with your comment since "the small strain" assumption is also used for the GPA module. So it's the AC statement coverage is too large. Moreover depending on how complicated the decomposition of the gradient of the displacement field tensor is, the GPA method might be too limited. I actually didn't thought about that aspect enough. For the moment, I will modify the the AC statement to be "Gradient of displacement field tensor decomposition" to target the module 2D strain calculation module specifically. I will check if the results from GPA could be considered in slightly more complex model and see if the AC should be changed to an UC.

**Comment by smiths** [comment]
Sounds like a good plan.

**Comment by slimpotatoes** [comment]
Matching MIS - MG done
